language: node_js

node_js:
  - '10'

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # faster npm install
  - yarn config set no-progress

script: yarn test-with-coverage

after_success: yarn coverage
